package:
    name: garmin_app
    version: "0.0.4.1"

#build:
    #number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
    git_url: ../

requirements:
  build:
    - python
    - numpy
    - libpython # [py2k and win]
    - setuptools
    - stravalib
    - python-dateutil

  run:
    - python
    - numpy
    - python-dateutil
    - pytz
    - stravalib

test:
  imports:
    - garmin_app

  requires:
   - nose

  commands:
   - nosetests ./tests/*.py garmin_app/*.py

#about
  #home: http://pandas.pydata.org
  #license: BSD
